### PR TITLE
Removing Chartbeat since contract ended

### PR DESCRIPTION
**Pull request by spra85**
@daytonn @collin @kand @jmelvnsn @shawncook @MelizzaP ... por favor 👍

### CODE REVIEW

**Comment by MelizzaP** [comment]
LGTM, but it looks like travis is not as into it

**Comment by kand** [comment]
👍 

No `.travis.yml` here to run, so I think it's failing on some invalid default config. If we want to use travis here we'll need to setup that file.

**Comment by collin** [comment]
I added travis on this PR: https://github.com/theonion/bulbs-public-analytics-manager/pull/9

**Comment by collin** [comment]
But we ended up not merging it.
travis yml that works for this project:
```yml
language: node_js
node_js:
- '5.1'
- '5.9'
sudo: false
before_script:
- bower install
- npm install
script:
- npm test
cache:
  directories:
  - node_modules
  - bower_components
```

**Comment by collin** [comment]
👍

**Pull request merged**
