### PR TITLE
add set dimension

### PR DESCRIPTION
**Pull request by brycedorn**

### CODE REVIEW

**Comment by brycedorn** [comment]
@jmelvnsn @spra85 👀 pls, used in bulbs pr

**Comment by jmelvnsn** [comment]
lgtm. although i'm not entirely sure what's going here. could you provide some more info?

**Comment by brycedorn** [comment]
this is just adding the method to the `analyticsManager` - we're calling `trackPageview` via it so it's expected that other methods should be wrapped within it also.

mostly just allows abstracting this layer instead of calling `ga` directly alongside `analyticsManager`

**Comment by jmelvnsn** [comment]
👍

**Pull request merged**
